//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from asm8086.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="asm8086Parser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface Iasm8086Listener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] asm8086Parser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] asm8086Parser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] asm8086Parser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] asm8086Parser.LineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruction([NotNull] asm8086Parser.InstructionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruction([NotNull] asm8086Parser.InstructionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.lbl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLbl([NotNull] asm8086Parser.LblContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.lbl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLbl([NotNull] asm8086Parser.LblContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.assemblerdirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblerdirective([NotNull] asm8086Parser.AssemblerdirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.assemblerdirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblerdirective([NotNull] asm8086Parser.AssemblerdirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.rw"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRw([NotNull] asm8086Parser.RwContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.rw"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRw([NotNull] asm8086Parser.RwContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.rb"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRb([NotNull] asm8086Parser.RbContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.rb"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRb([NotNull] asm8086Parser.RbContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.rs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRs([NotNull] asm8086Parser.RsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.rs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRs([NotNull] asm8086Parser.RsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.cseg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCseg([NotNull] asm8086Parser.CsegContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.cseg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCseg([NotNull] asm8086Parser.CsegContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.dseg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDseg([NotNull] asm8086Parser.DsegContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.dseg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDseg([NotNull] asm8086Parser.DsegContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.dw"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDw([NotNull] asm8086Parser.DwContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.dw"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDw([NotNull] asm8086Parser.DwContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.db"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDb([NotNull] asm8086Parser.DbContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.db"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDb([NotNull] asm8086Parser.DbContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.dd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDd([NotNull] asm8086Parser.DdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.dd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDd([NotNull] asm8086Parser.DdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.equ"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqu([NotNull] asm8086Parser.EquContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.equ"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqu([NotNull] asm8086Parser.EquContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.if_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_([NotNull] asm8086Parser.If_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.if_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_([NotNull] asm8086Parser.If_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.assemblerexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblerexpression([NotNull] asm8086Parser.AssemblerexpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.assemblerexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblerexpression([NotNull] asm8086Parser.AssemblerexpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.assemblerlogical"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblerlogical([NotNull] asm8086Parser.AssemblerlogicalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.assemblerlogical"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblerlogical([NotNull] asm8086Parser.AssemblerlogicalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.assemblerterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblerterm([NotNull] asm8086Parser.AssemblertermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.assemblerterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblerterm([NotNull] asm8086Parser.AssemblertermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.endif"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEndif([NotNull] asm8086Parser.EndifContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.endif"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEndif([NotNull] asm8086Parser.EndifContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.end"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnd([NotNull] asm8086Parser.EndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.end"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnd([NotNull] asm8086Parser.EndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.org"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrg([NotNull] asm8086Parser.OrgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.org"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrg([NotNull] asm8086Parser.OrgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.title"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTitle([NotNull] asm8086Parser.TitleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.title"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTitle([NotNull] asm8086Parser.TitleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInclude([NotNull] asm8086Parser.IncludeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInclude([NotNull] asm8086Parser.IncludeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.expressionlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionlist([NotNull] asm8086Parser.ExpressionlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.expressionlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionlist([NotNull] asm8086Parser.ExpressionlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabel([NotNull] asm8086Parser.LabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabel([NotNull] asm8086Parser.LabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] asm8086Parser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] asm8086Parser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.multiplyingExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplyingExpression([NotNull] asm8086Parser.MultiplyingExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.multiplyingExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplyingExpression([NotNull] asm8086Parser.MultiplyingExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgument([NotNull] asm8086Parser.ArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgument([NotNull] asm8086Parser.ArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.ptr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPtr([NotNull] asm8086Parser.PtrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.ptr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPtr([NotNull] asm8086Parser.PtrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.dollar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDollar([NotNull] asm8086Parser.DollarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.dollar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDollar([NotNull] asm8086Parser.DollarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.register_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRegister_([NotNull] asm8086Parser.Register_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.register_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRegister_([NotNull] asm8086Parser.Register_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] asm8086Parser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] asm8086Parser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName([NotNull] asm8086Parser.NameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName([NotNull] asm8086Parser.NameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] asm8086Parser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] asm8086Parser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpcode([NotNull] asm8086Parser.OpcodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpcode([NotNull] asm8086Parser.OpcodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.rep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRep([NotNull] asm8086Parser.RepContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.rep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRep([NotNull] asm8086Parser.RepContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComment([NotNull] asm8086Parser.CommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComment([NotNull] asm8086Parser.CommentContext context);
}
