//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from asm8086.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="Iasm8086Listener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class asm8086BaseListener : Iasm8086Listener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] asm8086Parser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] asm8086Parser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLine([NotNull] asm8086Parser.LineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLine([NotNull] asm8086Parser.LineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruction([NotNull] asm8086Parser.InstructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruction([NotNull] asm8086Parser.InstructionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.lbl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLbl([NotNull] asm8086Parser.LblContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.lbl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLbl([NotNull] asm8086Parser.LblContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.assemblerdirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssemblerdirective([NotNull] asm8086Parser.AssemblerdirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.assemblerdirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssemblerdirective([NotNull] asm8086Parser.AssemblerdirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.rw"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRw([NotNull] asm8086Parser.RwContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.rw"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRw([NotNull] asm8086Parser.RwContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.rb"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRb([NotNull] asm8086Parser.RbContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.rb"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRb([NotNull] asm8086Parser.RbContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.rs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRs([NotNull] asm8086Parser.RsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.rs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRs([NotNull] asm8086Parser.RsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.cseg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCseg([NotNull] asm8086Parser.CsegContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.cseg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCseg([NotNull] asm8086Parser.CsegContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.dseg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDseg([NotNull] asm8086Parser.DsegContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.dseg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDseg([NotNull] asm8086Parser.DsegContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.dw"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDw([NotNull] asm8086Parser.DwContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.dw"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDw([NotNull] asm8086Parser.DwContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.db"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDb([NotNull] asm8086Parser.DbContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.db"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDb([NotNull] asm8086Parser.DbContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.dd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDd([NotNull] asm8086Parser.DdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.dd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDd([NotNull] asm8086Parser.DdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.equ"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqu([NotNull] asm8086Parser.EquContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.equ"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqu([NotNull] asm8086Parser.EquContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.if_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_([NotNull] asm8086Parser.If_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.if_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_([NotNull] asm8086Parser.If_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.assemblerexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssemblerexpression([NotNull] asm8086Parser.AssemblerexpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.assemblerexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssemblerexpression([NotNull] asm8086Parser.AssemblerexpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.assemblerlogical"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssemblerlogical([NotNull] asm8086Parser.AssemblerlogicalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.assemblerlogical"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssemblerlogical([NotNull] asm8086Parser.AssemblerlogicalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.assemblerterm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssemblerterm([NotNull] asm8086Parser.AssemblertermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.assemblerterm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssemblerterm([NotNull] asm8086Parser.AssemblertermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.endif"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndif([NotNull] asm8086Parser.EndifContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.endif"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndif([NotNull] asm8086Parser.EndifContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.end"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnd([NotNull] asm8086Parser.EndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.end"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnd([NotNull] asm8086Parser.EndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.org"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrg([NotNull] asm8086Parser.OrgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.org"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrg([NotNull] asm8086Parser.OrgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.title"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTitle([NotNull] asm8086Parser.TitleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.title"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTitle([NotNull] asm8086Parser.TitleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.include"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInclude([NotNull] asm8086Parser.IncludeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.include"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInclude([NotNull] asm8086Parser.IncludeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.expressionlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionlist([NotNull] asm8086Parser.ExpressionlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.expressionlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionlist([NotNull] asm8086Parser.ExpressionlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabel([NotNull] asm8086Parser.LabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabel([NotNull] asm8086Parser.LabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] asm8086Parser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] asm8086Parser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.multiplyingExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplyingExpression([NotNull] asm8086Parser.MultiplyingExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.multiplyingExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplyingExpression([NotNull] asm8086Parser.MultiplyingExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument([NotNull] asm8086Parser.ArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument([NotNull] asm8086Parser.ArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.ptr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPtr([NotNull] asm8086Parser.PtrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.ptr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPtr([NotNull] asm8086Parser.PtrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.dollar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDollar([NotNull] asm8086Parser.DollarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.dollar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDollar([NotNull] asm8086Parser.DollarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.register_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRegister_([NotNull] asm8086Parser.Register_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.register_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRegister_([NotNull] asm8086Parser.Register_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] asm8086Parser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] asm8086Parser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterName([NotNull] asm8086Parser.NameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitName([NotNull] asm8086Parser.NameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] asm8086Parser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] asm8086Parser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.opcode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpcode([NotNull] asm8086Parser.OpcodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.opcode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpcode([NotNull] asm8086Parser.OpcodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.rep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRep([NotNull] asm8086Parser.RepContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.rep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRep([NotNull] asm8086Parser.RepContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="asm8086Parser.comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComment([NotNull] asm8086Parser.CommentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="asm8086Parser.comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComment([NotNull] asm8086Parser.CommentContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
