//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from asm8086.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="asm8086Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface Iasm8086Visitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg([NotNull] asm8086Parser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine([NotNull] asm8086Parser.LineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction([NotNull] asm8086Parser.InstructionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.lbl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLbl([NotNull] asm8086Parser.LblContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.assemblerdirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssemblerdirective([NotNull] asm8086Parser.AssemblerdirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.rw"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRw([NotNull] asm8086Parser.RwContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.rb"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRb([NotNull] asm8086Parser.RbContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.rs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRs([NotNull] asm8086Parser.RsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.cseg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCseg([NotNull] asm8086Parser.CsegContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.dseg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDseg([NotNull] asm8086Parser.DsegContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.dw"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDw([NotNull] asm8086Parser.DwContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.db"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDb([NotNull] asm8086Parser.DbContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.dd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDd([NotNull] asm8086Parser.DdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.equ"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqu([NotNull] asm8086Parser.EquContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.if_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_([NotNull] asm8086Parser.If_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.assemblerexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssemblerexpression([NotNull] asm8086Parser.AssemblerexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.assemblerlogical"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssemblerlogical([NotNull] asm8086Parser.AssemblerlogicalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.assemblerterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssemblerterm([NotNull] asm8086Parser.AssemblertermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.endif"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEndif([NotNull] asm8086Parser.EndifContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.end"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnd([NotNull] asm8086Parser.EndContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.org"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrg([NotNull] asm8086Parser.OrgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.title"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTitle([NotNull] asm8086Parser.TitleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInclude([NotNull] asm8086Parser.IncludeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.expressionlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionlist([NotNull] asm8086Parser.ExpressionlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabel([NotNull] asm8086Parser.LabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] asm8086Parser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.multiplyingExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplyingExpression([NotNull] asm8086Parser.MultiplyingExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] asm8086Parser.ArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.ptr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPtr([NotNull] asm8086Parser.PtrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.dollar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDollar([NotNull] asm8086Parser.DollarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.register_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRegister_([NotNull] asm8086Parser.Register_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] asm8086Parser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName([NotNull] asm8086Parser.NameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] asm8086Parser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpcode([NotNull] asm8086Parser.OpcodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.rep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRep([NotNull] asm8086Parser.RepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="asm8086Parser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComment([NotNull] asm8086Parser.CommentContext context);
}
